### ISSUE TITLE
Error during compilaton x86

### ISSUE THREAD

**Issue by DimastyK** [tomm/fab-agon-emulator#54]
fab-agon-emulator.exe said:
thread 'main' panicked at src\vdp_interface.rs:59:77:
called `Result::unwrap()` on an `Err` value: LoadLibraryExW { source: Os { code:
 193, kind: Uncategorized, message: "%1 не является приложением Win32." } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by maxgerhardt** [comment]
CC @tomm it seems like when I build the emulator in MSys2 [per instructions](https://github.com/tomm/fab-agon-emulator/blob/main/docs/compiling.md#compiling-for-windows), it hard compiles in some paths within the MSys2 filesystem which od not exist, resulting in LoadLibraryExW not finding the file.

```
C:\Users\Max\Downloads\fab-agon-2>fab-agon-emulator.exe --verbose
VDP firmware: "C:/msys64/home/Max/work/fab-agon-emulator\\share\\fab-agon-emulator\\vdp_console8.so"
thread 'main' panicked at src\vdp_interface.rs:59:77:
called `Result::unwrap()` on an `Err` value: LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Can the emulator be made to serach in just the relative `firmware` directory instead of searching for compile-time generated paths?

**Comment by maxgerhardt** [comment]
Nevermind, I did a `make clean` and `make -j8` again and the binary fixed itself up. Might have to do with running `PREFIX=/home/Max/work/fab-agon-emulator make` beforehand.

**Comment by DimastyK** [comment]
> Nevermind, I did a `make clean` and `make -j8` again and the binary fixed itself up. Might have to do with running `PREFIX=/home/Max/work/fab-agon-emulator make` beforehand.

well, I managed issue, compiled .exe requires some library from mingw32:
libstdc++-6.dll
libgcc_s_dw2-1.dll
libwinpthread-1.dll
SDL2.dll

btw. emulator crashes if plot routine outside of screen.
